#!/bin/bash
#Made by Ariyan Pegu for PUBG Mobile
#############################
fgred=`echo "\033[31m"`
red='\033[1;31m'
yellow='\033[1;33m'
blue='\033[1;34m'
#############################
DIR='/storage/emulated/0/.antiC'
if [ -d "$DIR" ]; then
echo ""
else
mkdir /storage/emulated/0/.antiC
fi
DIR='/storage/emulated/0/.antiC/libUE4.so'
if [ -d "$DIR" ]; then
echo ""
else
su -c cp -r /data/data/com.tencent.ig/lib/* /storage/emulated/0/.antiC/
fi
COUNT=50
fixPUBGM()
{
su -c cp -r /storage/emulated/0/.antiC/libBugly.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libcubehawk.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libgamemaster.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libgcloud.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libhelpshiftlistener.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libIMSDK.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/liblbs.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libnpps-jni.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libst-engine.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libswappy.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libTDataMaster.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libtersafe.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libtgpa.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libtprt.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libUE4.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libvlink.so /data/data/com.tencent.ig/lib/
su -c chmod 755 /data/data/com.tencent.ig/lib/*
su -c chmod 660 /data/data/com.tencent.ig/databases/*
su -c chmod 660 /data/data/com.tencent.ig/shared_prefs/*
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/*
su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_170_1.1.0.14553_20201116222655_1811727790_cures.ifs.res
su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_1.1.0.14551.pak
su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_1.1.0.14550.pak
su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_1.1.0.14552.pak
su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_1.1.0.14553.pak
sleep 5
}

blockDATA()
{
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json
su -c rm -rf /data/data/com.tencent.ig/files
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/*
su -c cp -r BLOCK /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/dns.txt
su -c touch /data/data/com.tencent.ig/files
su -c touch /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist
su -c touch /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json
su -c touch /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json
echo "嚙踝蕭嚙緲嚙踝蕭嚙踝蕭嚙踝蕭 嚙諍改蕭嚙踝蕭嚙?&嚙踝蕭嚙緲嚙踝蕭嚙? 嚙踝蕭嚙窯?嚙綞(嚙踝蕭]j蛁}嚙窮zv嚙踝蕭'!y嚙稷嚙踝蕭+"> /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini
su -c chmod 440 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/dns.txt
su -c chmod 000 /data/data/com.tencent.ig/files
su -c chmod 000 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist
su -c chmod 000 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json
su -c chmod 000 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json
su -c chmod 444 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android/AntiCheat.ini
sleep 5
}

modPUBGM()
{
su -c cp -r /data/data/com.tencent.ig/lib/libBugly.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libcubehawk.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libgamemaster.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libgcloud.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libhelpshiftlistener.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libIMSDK.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/liblbs.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libnpps-jni.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libst-engine.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libswappy.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libTDataMaster.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libtersafe.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libtgpa.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libtprt.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libUE4.so /storage/emulated/0/.antiC/
su -c cp -r /data/data/com.tencent.ig/lib/libvlink.so /storage/emulated/0/.antiC/
su -c rm -rf /data/data/com.tencent.ig/lib/libBugly.so
su -c rm -rf /data/data/com.tencent.ig/lib/libcubehawk.so
su -c rm -rf /data/data/com.tencent.ig/lib/libgamemaster.so
su -c rm -rf /data/data/com.tencent.ig/lib/libgcloud.so
su -c rm -rf /data/data/com.tencent.ig/lib/libhelpshiftlistener.so
su -c rm -rf /data/data/com.tencent.ig/lib/libIMSDK.so
su -c rm -rf /data/data/com.tencent.ig/lib/liblbs.so
su -c rm -rf /data/data/com.tencent.ig/lib/libnpps-jni.so
su -c rm -rf /data/data/com.tencent.ig/lib/libst-engine.so
su -c rm -rf /data/data/com.tencent.ig/lib/libswappy.so
su -c rm -rf /data/data/com.tencent.ig/lib/libTDataMaster.so
su -c rm -rf /data/data/com.tencent.ig/lib/libtersafe.so
su -c rm -rf /data/data/com.tencent.ig/lib/libtgpa.so
su -c rm -rf /data/data/com.tencent.ig/lib/libtprt.so
su -c rm -rf /data/data/com.tencent.ig/lib/libUE4.so
su -c rm -rf /data/data/com.tencent.ig/lib/libvlink.so
su -c chmod 000 /data/data/com.tencent.ig/lib/*
su -c chmod 000 /data/data/com.tencent.ig/databases/*
su -c chmod 000 /data/data/com.tencent.ig/shared_prefs/*
su -c chmod 000 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_170_1.1.0.14553_20201116222655_1811727790_cures.ifs.res
su -c chmod 000 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_1.1.0.14551.pak
su -c chmod 000 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_1.1.0.14552.pak
su -c chmod 000 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_1.1.0.14553.pak
sleep 5
}
########################################################################################
clear
clear
printf "$yellow
╭━━━━┳━━━┳━━━╮ ╭━━━━┳━━━┳━━━┳╮╱╱╭━━━╮ ╭╮╱╱╭╮╱╭╮
┃╭╮╭╮┃╭━╮┃╭━╮┃ ┃╭╮╭╮┃╭━╮┃╭━╮┃┃╱╱┃╭━╮┃ ┃╰╮╭╯┃╭╯┃
╰╯┃┃╰┫┃╱╰┫╰━━╮ ╰╯┃┃╰┫┃╱┃┃┃╱┃┃┃╱╱┃╰━━╮ ╰╮┃┃╭╯╰╮┃
╱╱┃┃╱┃┃╱╭╋━━╮┃ ╱╱┃┃╱┃┃╱┃┃┃╱┃┃┃╱╭╋━━╮┃ ╱┃╰╯┃╱╱┃┃
╱╱┃┃╱┃╰━╯┃╰━╯┃ ╱╱┃┃╱┃╰━╯┃╰━╯┃╰━╯┃╰━╯┃ ╱╰╮╭╯╱╭╯╰╮
╱╱╰╯╱╰━━━┻━━━╯ ╱╱╰╯╱╰━━━┻━━━┻━━━┻━━━╯ ╱╱╰╯╱╱╰━━╯\n";
sleep 1
echo 
echo "$red"
echo "𝐏𝐀𝐓𝐂𝐇-『𝐏𝐔𝐁𝐆 𝐌𝐎𝐁𝐈𝐋𝐄 𝐆𝐋𝐎𝐁𝐀𝐋 𝐕𝐄𝐑𝐒𝐈𝐎𝐍』\n"
echo "$yellow 1/ 𝙸𝙽𝙹𝙴𝙲𝚃 𝙰𝙽𝚃𝙸𝙱𝙰𝙽\n"    
echo " 2/ 𝚁𝙴𝚂𝚃𝙾𝚁𝙴 𝙰𝙽𝚃𝙸𝙱𝙰𝙽\n"    
echo " 3/ 𝚁𝙴𝚂𝙴𝚃 𝙶𝚄𝙴𝚂𝚃\n"
echo " 4/ 𝙵𝙸𝚇 𝙲𝚁𝙰𝚂𝙷\n"
############################# 
echo "$read"
read -s version
if [[ $version == 1 ]]; then
echo "$blue\n𝐒𝐓𝐀𝐑𝐓𝐈𝐍𝐆...\n"
echo ""
echo "𝐓𝐡𝐚𝐧𝐤𝐬 𝐟𝐨𝐫 𝐔𝐬𝐢𝐧𝐠 𝐓𝐂𝐒 𝐓𝐨𝐨𝐥𝐬 𝐕-1"
echo "𝐏𝐥𝐞𝐚𝐬𝐞 𝐖𝐚𝐢𝐭"
echo "\n"
sleep 5
echo "‡ 𝐏𝐥𝐚𝐲 𝐒𝐦𝐚𝐫𝐭, 𝐀𝐯𝐨𝐢𝐝 𝐑𝐞𝐩𝐨𝐫𝐭𝐬 ‡"
sleep 2
echo "$yellow"
echo "\n𝐑𝐞𝐩𝐚𝐢𝐫𝐢𝐧𝐠 𝐏𝐔𝐁𝐆𝐌 𝐃𝐀𝐓𝐀...\n"
fixPUBGM
echo "𝐁𝐋𝐎𝐂𝐊 𝐈𝐍𝐂𝐎𝐌𝐈𝐍𝐆 𝐆𝐀𝐌𝐄 𝐃𝐀𝐓𝐀\n"
blockDATA
printf "\n★ Keep Playing Don't Exit MT Manager/Shell ★\n\n";
printf "$red★𝐒𝐓𝐀𝐑𝐓 𝐏𝐔𝐁𝐆 𝐌𝐎𝐁𝐈𝐋𝐄 𝐆𝐋𝐎𝐁𝐀𝐋★\n";
sleep 3
am start -n com.tencent.ig/com.epicgames.ue4.SplashActivity
sleep 20
modPUBGM
echo "$blue"
sleep 1
echo "𝐀𝐍𝐓𝐈𝐁𝐀𝐍 𝐀𝐂𝐓𝐈𝐕𝐄 𝐒𝐔𝐂𝐄𝐒𝐒𝐅𝐔𝐋𝐋..."
echo
echo " 0%"
echo "▉▉▉▉ 10%"
sleep 0.5
echo "▉▉▉▉▉▉▉▉ 15%"
sleep 0.5
echo "▉▉▉▉▉▉▉▉▉▉▉▉ 30%"
sleep 0.5
echo "▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 45%"
sleep 0.5
echo "▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 60%"
sleep 0.5
echo "▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 75%"
sleep 0.5
echo "▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 80%"
sleep 0.5
echo "▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 100%"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
sleep 0.5
echo
su -c rm -rf /data/data/com.tencent.ig/cache/*
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/cache/*
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/LightData/*
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs/*
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs0/*
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferEifs1/*
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo/*
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/TableDatas/*
sleep 0.5
echo "𝐘𝐎𝐔 𝐂𝐀𝐍 𝐄𝐗𝐈𝐓 𝐌𝐓 𝐌𝐀𝐍𝐀𝐆𝐄𝐑"
echo "$red"
sleep 1
am force-stop com.termux

elif [[ $version == 2 ]]; then
echo "$blue"
echo "𝐑𝐄𝐒𝐓𝐎𝐑𝐄 𝐈𝐍𝐉𝐄𝐂𝐓𝐈𝐎𝐍 𝐃𝐀𝐓𝐀 𝐅𝐈𝐋𝐄𝐒"
echo
su -c cp -r /storage/emulated/0/.antiC/libBugly.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libcubehawk.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libgamemaster.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libgcloud.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libhelpshiftlistener.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libIMSDK.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/liblbs.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libnpps-jni.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libst-engine.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libswappy.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libTDataMaster.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libtersafe.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libtgpa.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libtprt.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libUE4.so /data/data/com.tencent.ig/lib/
su -c cp -r /storage/emulated/0/.antiC/libvlink.so /data/data/com.tencent.ig/lib/
su -c chmod 755 /data/data/com.tencent.ig/lib/*
su -c chmod 660 /data/data/com.tencent.ig/databases/*
su -c chmod 660 /data/data/com.tencent.ig/shared_prefs/*
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/apollo_reslist.flist
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/filelist.json
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/PufferFileList.json
su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora/*
su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/1375135419_170_1.1.0.14553_20201116222655_1811727790_cures.ifs.res
su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/core_patch_1.1.0.14551.pak
su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_1.1.0.14550.pak
su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_1.1.0.14552.pak
su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/game_patch_1.1.0.14553.pak
echo ""
sleep 5
echo "𝐈𝐍𝐉𝐄𝐂𝐓𝐈𝐎𝐍 𝐑𝐄𝐒𝐓𝐎𝐑𝐄 𝐒𝐔𝐂𝐄𝐒𝐒𝐅𝐔𝐋𝐋"
echo ""
echo "──𝐓𝐌𝐂𝐋𝐎𝐔𝐃-𝐒𝐓𝐎𝐑𝐄"
echo "$red"
sleep 1
am force-stop com.termux

elif [[ $version == 3 ]]; then
echo "$blue"
sleep 2
GUEST="/data/data/com.tencent.ig/shared_prefs/device_id.xml"
rm -rf $GUEST
echo "<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name=\"random\"></string>
    <string name=\"install\"></string>
    <string name=\"uuid\">$RANDOM$RANDOM-$RANDOM-$RANDOM-$RANDOM-$RANDOM$RANDOM$RANDOM</string>
</map>" > $GUEST
rm -rf /data/data/com.tencent.ig/databases
rm -rf /data/media/0/Android/data/com.tencent.ig/files/login-identifier.txt
echo
echo "GUEST ACCOUNT RESET SUCESSFULL"
echo ""
echo "──𝐓𝐌𝐂𝐋𝐎𝐔𝐃-𝐒𝐓𝐎𝐑𝐄"
echo "$red"
sleep 1
am force-stop com.termux

elif [[ $version == 4 ]]; then
echo "$blue\n"
sleep 2
rm -rf /data/data/com.tencent.ig/app_crashrecord
rm -rf /data/data/com.tencent.ig/files

#MAKE_DATA
touch /data/data/com.tencent.ig/app_crashrecord
touch /data/data/com.tencent.ig/files

#PERMISSION_CHANG
chmod 000 /data/data/com.tencent.ig/app_crashrecord
chmod 000 /data/data/com.tencent.ig/files
echo "PUBG MOBILE CRASH FIX SUCESS"
echo ""
echo "──𝐓𝐌𝐂𝐋𝐎𝐔𝐃-𝐒𝐓𝐎𝐑𝐄"
echo "$red"
sleep 1
am force-stop com.termux

elif [[ $version == * ]]; then
echo "Invalid Option"
fi
##########################################################
